python -m dialoop.cli novel.txt \
  --output labeled_test.txt \
  --annotations-output .dialoop/annotations.jsonl \
  --batch-size 1 \
  --max-tool-steps 20 \
  --max-iterations 1344 \
  --protocol auto \
  --base-url http://172.31.102.189:11434/v1 \
  --api-key ollama \
  --model qwen3:32b \
  --model-timeout 360